// This is a simple script to help initialize Convex
console.log("Initializing Convex configuration...");

const fs = require('fs');
const path = require('path');

// Ensure the _generated directory exists
const generatedDir = path.join(__dirname, 'convex', '_generated');
if (!fs.existsSync(generatedDir)) {
  fs.mkdirSync(generatedDir, { recursive: true });
}

// Create a basic initialization for convex
const initCode = `
// This file would normally be generated by Convex CLI
// We're creating a basic version manually

import { ConvexReactClient } from 'convex/react';

// Create a Convex client using the API URL from your dashboard
export const convex = new ConvexReactClient(process.env.NEXT_PUBLIC_CONVEX_URL || "https://adorable-spider-894.convex.cloud");
`;

fs.writeFileSync(path.join(__dirname, 'convex', 'init.js'), initCode);
console.log("Created convex/init.js");

console.log("Convex initialization complete. You can now run your project with:");
console.log("node server.js"); 